///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PruebaConsola
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CargaDatos recording.
    /// </summary>
    [TestModule("c9fcb179-1c50-4f4a-839d-062258416dac", ModuleType.Recording, 1)]
    public partial class CargaDatos : ITestModule
    {
        /// <summary>
        /// Holds an instance of the RepoCargaInicial repository.
        /// </summary>
        public static RepoCargaInicial repo = RepoCargaInicial.Instance;

        static CargaDatos instance = new CargaDatos();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CargaDatos()
        {
            bat_lanzador = "lanzador_ab.bat";
            bat_a_ejecutar = "install_zone_fileQA2AR.bat";
            ArchivoResultado = "SalidaComando_AB.txt";
            modulo = "ab";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CargaDatos Instance
        {
            get { return instance; }
        }

#region Variables

        string _bat_lanzador;

        /// <summary>
        /// Gets or sets the value of variable bat_lanzador.
        /// </summary>
        [TestVariable("35361108-6ace-4121-b46a-d252f29aa87a")]
        public string bat_lanzador
        {
            get { return _bat_lanzador; }
            set { _bat_lanzador = value; }
        }

        string _bat_a_ejecutar;

        /// <summary>
        /// Gets or sets the value of variable bat_a_ejecutar.
        /// </summary>
        [TestVariable("356530f7-1236-4654-bf34-33e4315d04d0")]
        public string bat_a_ejecutar
        {
            get { return _bat_a_ejecutar; }
            set { _bat_a_ejecutar = value; }
        }

        string _ArchivoResultado;

        /// <summary>
        /// Gets or sets the value of variable ArchivoResultado.
        /// </summary>
        [TestVariable("3282984f-301b-4647-884b-d9b319e89e22")]
        public string ArchivoResultado
        {
            get { return _ArchivoResultado; }
            set { _ArchivoResultado = value; }
        }

        string _modulo;

        /// <summary>
        /// Gets or sets the value of variable modulo.
        /// </summary>
        [TestVariable("49240ba3-0dc4-4d37-a5ec-9f77552b0256")]
        public string modulo
        {
            get { return _modulo; }
            set { _modulo = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            LanzadorCarga.LanzaCargaInicial(bat_a_ejecutar, modulo, ArchivoResultado);
            Delay.Milliseconds(0);
            
            //LanzadorCarga.LazaCargaInicial(bat_lanzador, bat_a_ejecutar);
            //Delay.Milliseconds(0);
            
            LanzadorCarga.VerificaFinal(ArchivoResultado);
            Delay.Milliseconds(0);
            
            LanzadorCarga.RenombrarArchivo(ArchivoResultado);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
