///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PruebaConsola
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Localidades_AB recording.
    /// </summary>
    [TestModule("8fef05a5-585a-492c-9494-747dcda6dbb1", ModuleType.Recording, 1)]
    public partial class Localidades_AB : ITestModule
    {
        /// <summary>
        /// Holds an instance of the RepoCargaInicial repository.
        /// </summary>
        public static RepoCargaInicial repo = RepoCargaInicial.Instance;

        static Localidades_AB instance = new Localidades_AB();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Localidades_AB()
        {
            bat_a_ejecutar = "install_zone_fileQA2AR.bat";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Localidades_AB Instance
        {
            get { return instance; }
        }

#region Variables

        string _bat_a_ejecutar;

        /// <summary>
        /// Gets or sets the value of variable bat_a_ejecutar.
        /// </summary>
        [TestVariable("12212e3f-6de9-43e9-b8c2-99ddd741e9f8")]
        public string bat_a_ejecutar
        {
            get { return _bat_a_ejecutar; }
            set { _bat_a_ejecutar = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            LanzaCargaInicial();
            Delay.Milliseconds(0);
            
            VerificaFinal();
            Delay.Milliseconds(0);
            
            RenombrarArchivo();
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'cd \\{Return}' with focus on 'CWindowsSystem32CmdExe'.", repo.CWindowsSystem32CmdExe.SelfInfo, new RecordItemIndex(3));
            //repo.CWindowsSystem32CmdExe.Self.EnsureVisible();
            //Keyboard.Press("cd \\{Return}");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(4));
            //Delay.Duration(3000, false);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{RMenu down}{OemOpenBrackets}{LControlKey up}{RMenu up}{LControlKey up}{Return}' with focus on 'CWindowsSystem32CmdExe'.", repo.CWindowsSystem32CmdExe.SelfInfo, new RecordItemIndex(5));
            //repo.CWindowsSystem32CmdExe.Self.EnsureVisible();
            //Keyboard.Press("{LControlKey down}{RMenu down}{OemOpenBrackets}{LControlKey up}{RMenu up}{LControlKey up}{Return}");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(6));
            //Delay.Duration(3000, false);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'cd Carga_Inicial_QA\\Localidades{Return}'.", new RecordItemIndex(7));
            //Keyboard.Press("cd Carga_Inicial_QA\\Localidades{Return}");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(8));
            //Delay.Duration(3000, false);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'install_zone_fileQA2AR.bat C:\\Carga_Inicial_QA\\Localidades -localdevMSSQL ab > C:\\TEMP\\SalidaComando.txt{Return}' with focus on 'CWindowsSystem32CmdExe'.", repo.CWindowsSystem32CmdExe.SelfInfo, new RecordItemIndex(9));
            //repo.CWindowsSystem32CmdExe.Self.EnsureVisible();
            //Keyboard.Press("install_zone_fileQA2AR.bat C:\\Carga_Inicial_QA\\Localidades -localdevMSSQL ab > C:\\TEMP\\SalidaComando.txt{Return}");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{Akey}{LControlKey up}'.", new RecordItemIndex(10));
            //Keyboard.Press("{LControlKey down}{Akey}{LControlKey up}");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(11));
            //Delay.Duration(3000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
