///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace PruebaConsola
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the RepoCargaInicial element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("be1e33f6-9c4e-4826-bb67-c1d930e2906e")]
    public partial class RepoCargaInicial : RepoGenBaseFolder
    {
        static RepoCargaInicial instance = new RepoCargaInicial();
        RepoCargaInicialFolders.ExplorerAppFolder _explorer;
        RepoCargaInicialFolders.CWindowsSystem32CmdExeAppFolder _cwindowssystem32cmdexe;

        /// <summary>
        /// Gets the singleton class instance representing the RepoCargaInicial element repository.
        /// </summary>
        [RepositoryFolder("be1e33f6-9c4e-4826-bb67-c1d930e2906e")]
        public static RepoCargaInicial Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public RepoCargaInicial() 
            : base("RepoCargaInicial", "/", null, 0, false, "be1e33f6-9c4e-4826-bb67-c1d930e2906e", ".\\RepositoryImages\\RepoCargaInicialbe1e33f6.rximgres")
        {
            _explorer = new RepoCargaInicialFolders.ExplorerAppFolder(this);
            _cwindowssystem32cmdexe = new RepoCargaInicialFolders.CWindowsSystem32CmdExeAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("be1e33f6-9c4e-4826-bb67-c1d930e2906e")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("d69e3699-1b70-46ec-83ce-754a8a2fb789")]
        public virtual RepoCargaInicialFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }

        /// <summary>
        /// The CWindowsSystem32CmdExe folder.
        /// </summary>
        [RepositoryFolder("9e4d7d7f-2638-4f80-8689-015c975cde73")]
        public virtual RepoCargaInicialFolders.CWindowsSystem32CmdExeAppFolder CWindowsSystem32CmdExe
        {
            get { return _cwindowssystem32cmdexe; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class RepoCargaInicialFolders
    {
        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("d69e3699-1b70-46ec-83ce-754a8a2fb789")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _procesadordecomandosdewindows1veInfo;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/menubar[@processname='explorer']", parentFolder, 30000, null, true, "d69e3699-1b70-46ec-83ce-754a8a2fb789", "")
            {
                _procesadordecomandosdewindows1veInfo = new RepoItemInfo(this, "ProcesadorDeComandosDeWindows1Ve", "container[@controlid='40965']//toolbar[@accessiblename='Aplicaciones en ejecución']/button[@accessiblename>'Procesador de comandos de']", 30000, null, "4d06c000-bb39-46ad-9b1f-b28d8f9bf61f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d69e3699-1b70-46ec-83ce-754a8a2fb789")]
            public virtual Ranorex.MenuBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d69e3699-1b70-46ec-83ce-754a8a2fb789")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ProcesadorDeComandosDeWindows1Ve item.
            /// </summary>
            [RepositoryItem("4d06c000-bb39-46ad-9b1f-b28d8f9bf61f")]
            public virtual Ranorex.Button ProcesadorDeComandosDeWindows1Ve
            {
                get
                {
                    return _procesadordecomandosdewindows1veInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ProcesadorDeComandosDeWindows1Ve item info.
            /// </summary>
            [RepositoryItemInfo("4d06c000-bb39-46ad-9b1f-b28d8f9bf61f")]
            public virtual RepoItemInfo ProcesadorDeComandosDeWindows1VeInfo
            {
                get
                {
                    return _procesadordecomandosdewindows1veInfo;
                }
            }
        }

        /// <summary>
        /// The CWindowsSystem32CmdExeAppFolder folder.
        /// </summary>
        [RepositoryFolder("9e4d7d7f-2638-4f80-8689-015c975cde73")]
        public partial class CWindowsSystem32CmdExeAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new CWindowsSystem32CmdExe  folder.
            /// </summary>
            public CWindowsSystem32CmdExeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("CWindowsSystem32CmdExe", "/form[@title>'C:\\Windows\\System32\\cmd.e']", parentFolder, 30000, null, true, "9e4d7d7f-2638-4f80-8689-015c975cde73", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9e4d7d7f-2638-4f80-8689-015c975cde73")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9e4d7d7f-2638-4f80-8689-015c975cde73")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
